//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldStreet
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteMesa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClienteMesa()
        {
            this.HistorialEstadoMesa = new HashSet<HistorialEstadoMesa>();
        }
    
        public int ClienteMesaID { get; set; }
        public short MesaID { get; set; }
        public int CuentaID { get; set; }
        public Nullable<int> ReservacionID { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
        public virtual Mesas Mesas { get; set; }
        public virtual Reservacion Reservacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialEstadoMesa> HistorialEstadoMesa { get; set; }
    }
}
