//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldStreet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comanda
    {
        public int ComandaID { get; set; }
        public int CuentaID { get; set; }
        public short MenuID { get; set; }
        public int EmpleadoID { get; set; }
        public short Cantidad { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
